### ISSUE TITLE
Does this method rely too much on the internal and external parameters of the sensor

### ISSUE THREAD

**Issue by 2anchao** [aharley/simple_bev#1]

**Comment by aharley** [comment]
Can you explain your issue more, @2anchao ? I'm not sure I get it.

**Comment by 2anchao** [comment]
in autonomous driving, because of the complicated external environment， cameras might deviate from the calibrated position at runtime, bev_baseline use intrinsics and extrinsics to get bev feature, it's efficiency, but it robustness?

**Comment by aharley** [comment]
Ah, great comment. I think this is definitely something to think about -- it's a criticism that applies to probably all existing works doing a 2D-to-BEV transformation. 

You might be encouraged from Fig 6a of "Lift Splat Shoot", which shows that if you train with noise in the extrinsics, you can be robust to this type of noise at test time. 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/5279974/183156647-2588d175-3519-4b4e-a4e2-cf768664cc03.png">

> We show that it is possible to train our network such that it is resilient to
common sources of sensor error. [...] [We] show that by training with a large
amount of noise in the extrinsics (blue), the network becomes more robust to extrinsic
noise at test time.

"Lift, Splat, Shoot: Encoding Images from Arbitrary Camera Rigs by Implicitly Unprojecting to 3D" Philion and Fidler, ECCV 2020.

I'm quite sure you could show the same thing with our bev_baseline model, and you could probably also show a similar effect for the intrinsics.

**Comment by 2anchao** [comment]
Thanks for your answer and your great work.

**Comment by 2anchao** [comment]
I use resnet34 as backbone, get vehicle segmentation miou 45.4(only camera), resnet18 as beckbone get miou 43.2(only camera). I think it's a very good result.  
and I want to do some experiments on road segmentation, If convenient, please provide the road segmentation dataloader to me, thanks. my email is an_chao1994@163.com

**Comment by aharley** [comment]
That's a great result, @2anchao! I bet the model is quite fast too, because of the shallower backbone. If you make a paper, please remember to cite us! 😄 

We will try to add lane and road annotations to the repo soon.

**Comment by 2anchao** [comment]
I just do some experiments based on your work, Thank you for your work. if I has chance to make a paper, It's my pleasure to cite your paper.

can I get road annotations by follows:
![image](https://user-images.githubusercontent.com/37031491/185787574-2d4ae63c-f811-4783-9c8f-3b0e12001291.png)

**Comment by aharley** [comment]
Yes, that's the right part of the code. `lmap` might be very close to what you need.

**Comment by 2anchao** [comment]
I use lmap to generate road annotations, use res34 as backbone, get miou 74.2😄(only camera), happy!

**Comment by SunJ1025** [comment]
> I use lmap to generate road annotations, use res34 as backbone, get miou 74.2😄(only camera), happy!

Hi , may I ask you how did you use lmap to genereatw road annotations? very thanks.
