### ISSUE TITLE
When do you release model files and performance？

### ISSUE THREAD

**Issue by liwuhen** [aharley/simple_bev#2]

**Comment by aharley** [comment]
I think this should be possible next week!

**Comment by liwuhen** [comment]
Thank you for your work

**Comment by liwuhen** [comment]
Will you release the visualization module？

**Comment by aharley** [comment]
Yes

**Comment by aharley** [comment]
@liwuhen We added a few missing files, and added a readme. We will be adding the visualization scripts very soon as well. Perhaps you can try it out, and let us know how it goes.

**Comment by liwuhen** [comment]
Thank you for your work. I will try your suggestions
