### ISSUE TITLE
KeyError: 'H' in evaluation

### ISSUE THREAD

**Issue by BHC1205** [aharley/simple_bev#9]
hi,
The following error occurred when I used the recommended method for evaluation,
File "/home/zhwsh/code/simple_bev-main/nuscenesdataset.py", line 728, in sample_augmentation
    H, W = self.data_aug_conf['H'], self.data_aug_conf['W']
KeyError: 'H'

Then I noticed that there was no 'H''W' defined in "data_aug_conf",what's the value of them?
    data_aug_conf = {
        'final_dim': final_dim,
        'cams': ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT',
                 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT'],
        'ncams': ncams,
    }

**Comment by aharley** [comment]
By coincidence I think I fixed this just yesterday:
https://github.com/aharley/simple_bev/commit/eb969c9c3b63dfba0d72a71742412e60553e3bda

Can you pull and let me know if you still have the problem?

**Comment by BHC1205** [comment]
>works well ,thank you :D


 final trainval mean iou 55.79004151683923
